export const schools = [
  "Kunnamangalam HSS",
  "Markaz HSS Karanthur",
  "Markaz Girls HS Karanthur",
  "Govt. High School Nairkuzhi",
  "REC Govt. HSS, Chathamangalam",
  "AUPS Kunnamangalam",
  "AUPS Kunnamangalam East",
  "AMUPS Makkoottam",
  "AUPS Pilassery",
  "AUPS Koozhakode",
  "AUPS Choolur",
  "AUPS Malayamma",
  "AUPS Pazhur",
  "AUPS Chathamangalam",
  "GLPS Padanilam",
  "GLPS Chathamangalam",
  "GLPS Chenoth",
  "GLPS Erimala",
  "GLPS Poolakkode",
  "GLPS Pullannur",
  "GLPS Pullannur New",
  "GLPS Vellannur",
  "SGM LPS Karanthur",
  "AMLPS Karanthur",
  "AMLPS Kunnamangalam",
  "ALPS Peruvazhikadavu",
  "ALPS Kalarikandy",
  "ALPS Kolayi",
  "ALPS Choolur",
  "ALPS Keezhur",
  "ALPS Mavoor",
  "AMLP School Thathoor",
  "AMLPS Velliparamba",
  "GLPS Velliparamba",
  "ALPS Kuttikkattoor",
  "AMLPS Kuttikkattoor",
  "GHSS Kuttikkattoor",
  "GLPS Mundakkal",
  "GLPS Cherukulathoor",
  "GHSS Peringolom",
  "ALPS Cherukulathoor East",
  "ALPS Poovattuparamba",
  "ALPS Kayalam",
  "St. Xavier's UPS Peruvayal",
  "AMUPS Puthurmadam",
  "ALPS Perumanna",
  "AMLPS Arathilparamba",
  "AMLPS Vellayikkode",
  "GLPS Payyadimeethal",
  "EMS Govt. HSS Perumanna",
  "ALPS Paingottupuram",
  "GMUPS Mavoor",
  "GUPS Manakkad",
  "GLPS Kanni Paramba",
  "ALPS Kanni Paramba",
  "ALPS Aduvad",
  "GHSS Mavoor",
  "GLPS Valayannur",
  "GLPS Cheruppa",
  "ALPS Olavanna",
  "GLPS Olavanna",
  "GLPS Iringallur",
  "GHSS Iringallur",
  "GUPS Koodal Nadakkavu",
  "AUPS Pantheerankavu",
  "HSS Pantheerankavu",
  "AMLPS Kailamadam",
  "ALPS Kunnamkulangara",
  "AMUPS Kunnamkulangara",
  "AMLPS Thumbayil",
  "ALPS Odumbra",
  "AMUPS Kambliparamba",
  "GLPS Koodathumpara"
];
